name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "jruby-9.2.13.0"
        rails:
          - "5.0"
          - "5.1"
          - "5.2"
          - "6.0"
          - "6.1"
        exclude:
          - ruby: "2.7"
            rails: "5.0"
          - ruby: "2.7"
            rails: "5.1"
          - ruby: "2.7"
            rails: "5.2"
          - ruby: "jruby-9.2.13.0"
            rails: "6.1"
    name: Test Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-${{ hashFiles('Gemfile.lock', 'gemfiles/**.gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-
      - name: Run test suite
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          gem install bundler appraisal
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          ./cc-test-reporter before-build
          bundle exec rake db:reset spec:all yard:doctest
          ./cc-test-reporter after-build --exit-code $?
